spring.application.name=management
server.port=8080

# Database Configuration
spring.datasource.url = jdbc:mysql://localhost:3306/managementdb?createDatabaseIfNotExists=true
spring.datasource.username = root
spring.datasource.password = admin
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = false
spring.jpa.properties.hibernate.format_sql = true

# Logging Configuration
logging.level.root=WARN
logging.level.com.student.management=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javafullstack2121@gmail.com
spring.mail.password=ezmewxagsnofiljz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# API Documentation
app.version=1.0.0
app.name=Student Management API

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
